# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 16:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20160725_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
