# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160725_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topmenupage',
            options={'verbose_name': 'Despre Index Page'},
        ),
    ]
