# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcepagerelateddocument',
            old_name='link_document',
            new_name='document',
        ),
    ]
