# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160704_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSubPage',
            new_name='StandardPage',
        ),
    ]
