# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0012_auto_20160721_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutinitiativesindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutinitiativesindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='aboutinitiativesindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='aboutinitiativesindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutnetworknewsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutnetworknewsindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='aboutnetworknewsindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='aboutnetworknewsindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardblogindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='standardblogindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='standardblogindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='urbanblogindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='urbanblogindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='urbanblogindexpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='AboutIndexPage',
        ),
        migrations.DeleteModel(
            name='AboutInitiativesIndexPage',
        ),
        migrations.DeleteModel(
            name='AboutInitiativesIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='AboutNetworkNewsIndexPage',
        ),
        migrations.DeleteModel(
            name='AboutNetworkNewsIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='StandardBlogIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='UrbanBlogIndexPageRelatedLink',
        ),
    ]
