# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160721_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardBlogIndexPage',
            new_name='UniversalBlogIndexPage',
        ),
    ]
