# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_standardindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalblogpage',
            name='intro',
            field=models.CharField(blank=True, help_text='Text which will be visible as short description of the post', max_length=650, verbose_name='intro'),
        ),
    ]
