# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_universalblogpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalblogpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Text which will be visible as short description of the post', max_length=650, verbose_name='intro'),
        ),
    ]
