# Dev env compose file

version: '2'

volumes:
    pgdata:
    pglogs:
    postgis_data:

services:

    django:
        build:
            context: ./../../
            dockerfile: ./docker/stage/Dockerfile-stage
        volumes:
            - ./../../:/urbana
        working_dir: /urbana/urbana
        command: bash -c ". ../docker/stage/run_django.sh"
        ports:
            - 1080:80
            - 35729:35729
        depends_on:
            - pg_database
        env_file: stage.env

    pg_database:
        build:
            context: ./../common/postgis/
            dockerfile: Dockerfile-postgis
        # secret strings are in the file
        env_file: stage.env
        volumes:
            # override postgres image Dockerfile data volume
            - postgis_data:/var/lib/postgresql/data
            - pglogs:/var/log/postgresql
            - ../../dumps:/dumps  # volume mounted to get dump files out of container
        ports:
            # expose ports to the docker host for debug purposes
            - 5432:5432
